stages:
  - test

test:
  stage: test
  image: golang:${IMAGE_TAG}
  variables:
    IMAGE_TAG: "1.23.1"
    UT_MODE: "ci"
    UT_TAGS: ""
    UT_WORK_DIR: $CI_PROJECT_DIR
  script:
    - chmod +x ./scripts/test.sh
    - UT_WORK_DIR=$UT_WORK_DIR ./scripts/test.sh --mode $UT_MODE --tags $UT_TAGS

  artifacts:
    paths: code-coverage.html
    when: $UT_MODE == "ci+cover"

    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
        when: $UT_MODE == "ci+cover"
