
# default hostname
AppId: ""

Hack: ""

ShowErrCode: false

Http:
  Port: 8800
  Debug: false

Filename:
  Logger: "./ops.log" # output to stderr if empty
  Event: "./event.log"  # output to stdout if empty

Logger:
  # Debug = -4
  # Info  = 0
  Level: 0

  # print file line
  AddSource: false

  JsonFormat: false
  NoColor: false

MySql:
  User: root
  Password: 1234
  Host: localhost
  Port: 3306
  Database: testdata
  Debug: true

Redis:
  User: ""
  Password: ""
  Host: localhost
  Port: 6379

O11Y:
  Port: 2112

  # Optional, does not affect the main application startup if not set
  TraceHost: localhost
  TracePort: 3200
  EnableTrace: false

